name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        env:
          NEXT_PUBLIC_TMDB_TOKEN: ${{ secrets.NEXT_PUBLIC_TMDB_TOKEN }}
        run: yarn build

      - name: Run lint (ESLint)
        run: yarn lint

      # - name: Run tests
      #   run: yarn test  # Jest를 사용한 테스트 실행
