name: CI/CD Workflow

on:
  push:
    branches: 
      - main
      - dev
    pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
  # 설치 및 빌드/테스트/린트 작업을 하나의 job으로 처리
  build_and_test:
    runs-on: ubuntu-latest  # 최신 리눅스 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install  # yarn을 사용하여 종속성 설치

      - name: Build the project
        run: yarn build 

      - name: Run lint (ESLint)
        run: yarn lint  # ESLint로 코드 검사 (작업을 lint로 실행한다고 가정)

      # - name: Run tests
      #   run: yarn test  # Jest를 사용한 테스트 실행

   